config/routes.rb
Rails.application.routes.draw do
  
  root to:'home#index'
  

  resources :users 
  get 'signup' => 'users#create'
  get 'list' => 'users#index'
  get 'users/:id/posts' => 'users#posts', :as => :user_posts
  

  resources :posts do
    resources :comments
  end
  post 'postcomment' => 'comments#create'
  get 'newpost' => 'posts#new'
  get 'all' => 'posts#index'
  post 'all' => 'posts#index'
 

  resources :collections
  post 'newcollection' => 'collections#new'
  post 'destroycollection' => 'collections#destroy'
  get 'showcollection' => 'collections#show'

  resources :movies
  post 'newmovie' => 'movies#new'
  post 'destroymovie' => 'movies#destroy'

  resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'home/index'
 

 

end

app/models/collection.rb
class Collection
  include Mongoid::Document
  has_and_belongs_to_many :movies
  field :title, type: String
  field :slug, type: String
  validates :slug, presence: true
  def to_param
    slug
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_user, only: [:show]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    current_user
    @movies = @collection.movies
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.slug = @collection.title.downcase.gsub(' ','-')
    respond_to do |format|
      if @collection.save
        flash[:success] = 'Collection was successfully created.'
        format.html { redirect_to @collection}
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        flash[:success] = 'Collection was successfully updated.'
        format.html { redirect_to @collection}
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      flash[:success] = 'Collection destroyed'
      format.html { redirect_to collections_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find_by(slug: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:title, :slug, movie_ids: [])
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= simple_form_for(@collection, html: {class: 'form-vertical' }) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>
      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title, placeholder: 'Enter Collection Title' %>
  <%= f.association :movies, collection: @current_user.movies, as: :check_boxes %>
  <%= f.button :submit %>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Collections</h1>

<table class = 'table'>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.title %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form' %>

app/views/collections/show.html.erb
<p>
	Share this collection!
	<br><br><br>
  localhost:3000/collections/<%= @collection.slug%>
  <br><br><br>
  <strong><%= @collection.title %>:</strong><br>
</p>
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>