config/routes.rb
Rails.application.routes.draw do
  
  root to:'home#index'
  

  resources :users 
  get 'signup' => 'users#create'
  get 'list' => 'users#index'
  get 'users/:id/posts' => 'users#posts', :as => :user_posts
  

  resources :posts do
    resources :comments
  end
  post 'postcomment' => 'comments#create'
  get 'newpost' => 'posts#new'
  get 'all' => 'posts#index'
  post 'all' => 'posts#index'
 

  resources :collections
  post 'newcollection' => 'collections#new'
  post 'destroycollection' => 'collections#destroy'
  get 'showcollection' => 'collections#show'

  resources :movies
  post 'newmovie' => 'movies#new'
  post 'destroymovie' => 'movies#destroy'

  resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'home/index'
 

 

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  belongs_to :post 
  belongs_to :user
  field :username, type: String
  field :text, type: String
  field :score, type: Integer

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    post = Post.find(params[:post_id])
    @comments = post.comments
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @comments }
    end
  end

  def show
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @comment }
    end
  end

  def new
    @post = Post.find(params[:post_id])
    #2nd you build a new one
    @comment = Comment.new 


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /posts/:post_id/comments/:id/edit
  def edit
    #1st you retrieve the post thanks to params[:post_id]
    @post = Post.find(params[:post_id])
    #2nd you retrieve the comment thanks to params[:id]
    @comment = @post.comments.find(params[:id])
  end

  # POST /posts/:post_id/comments
  # POST /posts/:post_id/comments.xml
  def create
    #1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    #2nd you create the comment with arguments in params[:comment]
    @comment = post.comments.create(comment_params)
    @comment.user_id = @current_user._id
    @comment.username = @current_user.username

    @comment.save

    respond_to do |format|
      if @comment.save
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to([@comment.post, @comment], :notice => 'Comment was successfully created.') }
        #the key :location is associated to an array in order to build the correct route to the nested resource comment
        format.xml  { render :xml => @comment, :status => :created, :location => [@comment.post, @comment] }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/:post_id/comments/:id
  # PUT /posts/:post_id/comments/:id.xml
  def update
    #1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    #2nd you retrieve the comment thanks to params[:id]
    @comment = post.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(comment_params)
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
        format.html { redirect_to([@comment.post, @comment], :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/:post_id/comments/1
  # DELETE /posts/:post_id/comments/1.xml
  def destroy
    #1st you retrieve the post thanks to params[:post_id]
    post = Post.find(params[:post_id])
    #2nd you retrieve the comment thanks to params[:id]
    @comment = post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      #1st argument reference the path /posts/:post_id/comments/
      format.html { redirect_to(post_comments_url) }
      format.xml  { head :ok }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_comment
      #@comment = Comment.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :score, :commenter)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<!-- /posts/:post_id/comments/:id -->
<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Commenter</th>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.username %></td>
    <td><%= comment.text %></td>

    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to 'Show', [comment.post, comment] %></td>
    <!-- /posts/:post_id/comments/:id/edit -->
    <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment)%></td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to 'Destroy', [comment.post, comment], :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_post_comment_path %> <!-- /posts/:post_id/comments/new -->
<%= link_to 'Back', posts_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', post_comments_path(@post,@comment)%>

app/views/comments/show.html.erb
<p>
  <b>Commenter:</b>
  <%= @comment.username %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.text %>
</p>

<!-- /posts/:post_id/comments/:id/edit -->
<%= link_to 'Edit', edit_post_comment_path(@comment.post, @comment) %> |
<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', post_comments_path(@comment.post) %> 