config/routes.rb
Rails.application.routes.draw do
  
  root to:'home#index'
  

  resources :users 
  get 'signup' => 'users#create'
  get 'list' => 'users#index'
  get 'users/:id/posts' => 'users#posts', :as => :user_posts
  

  resources :posts do
    resources :comments
  end
  post 'postcomment' => 'comments#create'
  get 'newpost' => 'posts#new'
  get 'all' => 'posts#index'
  post 'all' => 'posts#index'
 

  resources :collections
  post 'newcollection' => 'collections#new'
  post 'destroycollection' => 'collections#destroy'
  get 'showcollection' => 'collections#show'

  resources :movies
  post 'newmovie' => 'movies#new'
  post 'destroymovie' => 'movies#destroy'

  resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'home/index'
 

 

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Paperclip
  include ActiveModel::SecurePassword

  before_save :encrypt_password
  has_many :posts
  has_many :comments
  has_many :movies
  has_mongoid_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "blank-profile-hi.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_secure_password
  validates :username, :email, :slug, presence: true
  validates :password, confirmation: true
  validates :username, uniqueness: {case_sensitive: false, message: 'That username is already taken.'}
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create } 
  validates :email, uniqueness: {message: 'That email is already taken.'}
  field :username, type: String
  field :email, type: String
  field :password_digest, type: String
  field :slug, type: String
  def to_param
    slug
  end
  def encrypt_password
    if password.present?
      self.password_digest = BCrypt::Password.create(password, :cost => 10)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :movies, :posts]
  skip_before_filter :require_user, :only => [:new, :create, :show]

  def index
  	@users = User.all
  end

  def posts
    @posts = @user.posts
  end

  def movies
    @movies = @user.movies
  end

  def show
    current_user
  end


  def new
  	@user = User.new
  end

  def edit
  end

  def create
  	@user = User.new(user_params)
    @user.slug = @user.username.downcase.gsub(' ','-')
  	respond_to do |format|
  		if @user.valid?
        @user.save
        session[:user_id] = @user.id
        flash[:success] = 'Welcome new user!'
  			format.html { redirect_to @user}
  			format.json { render :show, status: :created, location: @user }
  		else
  			format.html { render :new }
  			format.json { render json: @user.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = 'User was successfully destroyed.'
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(slug: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :slug, :username, :password, :password_confirmation, :avatar )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: {multipart: 'true', class: 'form-vertical' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :avatar, as: :file, placeholder: 'Your profile picture' %>
  <%= f.input :username, placeholder: 'Enter username' %>
  <%= f.input :email, placeholder: 'Enter email' %>
  <%= f.input :password, :label => 'Password',:placeholder => 'Password' %>
  <%= f.input :password_confirmation, :label => 'Confirm', placeholder: 'Confirm Password' %>
  <%= f.button :submit %>
  <% end %>
  

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users of Zlatos </h1>
<br>
<body> 
<br>
<br>
</body>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show ', user %></td>
        <td><%= link_to 'Posts ', user_posts_path(user.id) %></td>
        <% if user.email == @current_user.email %>
        <td><%= link_to 'Edit ', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy ', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/posts.html.erb
<h1> Posts from <%= @user.username %> </h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.score %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>Dashboard</h1>
<%= image_tag @user.avatar.url(:medium), class: 'img-circle', size: '300x300' %>
<br>
<br>
<p>
  <% if @user == @current_user %>
  <%= button_to('Create New Collection', newcollection_path, :class => 'btn btn-large btn-primary')%>
  <br><br>
  <%= button_to('Add New Movie?', newmovie_path, :class => 'btn btn-large btn-primary')%> 
  <strong>Your Favorite Movies:</strong>
  <% else %>
  <strong><%=@user.username%>'s Favorite Movies:</strong>
  <% end %>
</p>
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= button_to('Destroy?', movie, method: :delete, :class => 'btn btn-large btn-primary') %></td>
      </tr>
    <% end %>
  </tbody>
</table>