config/routes.rb
Rails.application.routes.draw do
  
  root to:'home#index'
  

  resources :users 
  get 'signup' => 'users#create'
  get 'list' => 'users#index'
  get 'users/:id/posts' => 'users#posts', :as => :user_posts
  

  resources :posts do
    resources :comments
  end
  post 'postcomment' => 'comments#create'
  get 'newpost' => 'posts#new'
  get 'all' => 'posts#index'
  post 'all' => 'posts#index'
 

  resources :collections
  post 'newcollection' => 'collections#new'
  post 'destroycollection' => 'collections#destroy'
  get 'showcollection' => 'collections#show'

  resources :movies
  post 'newmovie' => 'movies#new'
  post 'destroymovie' => 'movies#destroy'

  resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'home/index'
 

 

end

app/models/post.rb
class Post
  include Mongoid::Document
  belongs_to :user
  has_many :comments

  validates :title,  :presence => true
  validates :text, :presence => true, :length => { :minimum => 5 }
  
  field :title, type: String
  field :text, type: String
  field :score, type: Integer
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find_by(id: @post.user_id)
  end

  def new
  	@post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
  	@post = Post.new(post_params)
    @post.user_id = @current_user._id 
    @post.save
  	respond_to do |format|
  		if @post.save
  			format.html { redirect_to :controller => 'home', :action => 'index', notice: 'Post was successfully created.'}
  			format.json { render :show, status: :created, location: @post }
  		else
  			format.html { render :new }
  			format.json { render json: @post.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text, :score, :user_id, :id, :post)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post, url: posts/index do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', users_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<br><br>
</body>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.score %></td>
        <% if post.user_id == @current_user._id %>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Post', newpost_path %>
<%= link_to 'Home', root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>Score:</strong>
  <%= @post.score %>
</p>
<p>
  <strong>Created by:</strong>
  <%= @user.username if @user %>
</p>

<%= link_to 'Comments', post_comments_path(@post) %>